/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnRouteImport } from './routes/en'
import { Route as FrRouteImport } from './routes/fr'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RuRouteImport } from './routes/ru'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocaleSlugRouteImport } from './routes/$locale/$slug'
import { Route as ApiPublicCaseStatusRouteImport } from './routes/api/public/case-status'
import { Route as ApiPublicCreateCaseRouteImport } from './routes/api/public/create-case'
import { Route as ApiPublicUploadDocumentRouteImport } from './routes/api/public/upload-document'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RuRoute = RuRouteImport.update({
  id: '/ru',
  path: '/ru',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSlugRoute = LocaleSlugRouteImport.update({
  id: '/$locale/$slug',
  path: '/$locale/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCaseStatusRoute = ApiPublicCaseStatusRouteImport.update({
  id: '/api/public/case-status',
  path: '/api/public/case-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreateCaseRoute = ApiPublicCreateCaseRouteImport.update({
  id: '/api/public/create-case',
  path: '/api/public/create-case',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadDocumentRoute = ApiPublicUploadDocumentRouteImport.update({
  id: '/api/public/upload-document',
  path: '/api/public/upload-document',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/fr': typeof FrRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/ru': typeof RuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/api/public/case-status': typeof ApiPublicCaseStatusRoute
  '/api/public/create-case': typeof ApiPublicCreateCaseRoute
  '/api/public/upload-document': typeof ApiPublicUploadDocumentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/fr': typeof FrRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/ru': typeof RuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/api/public/case-status': typeof ApiPublicCaseStatusRoute
  '/api/public/create-case': typeof ApiPublicCreateCaseRoute
  '/api/public/upload-document': typeof ApiPublicUploadDocumentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRoute
  '/fr': typeof FrRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/ru': typeof RuRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$slug': typeof LocaleSlugRoute
  '/api/public/case-status': typeof ApiPublicCaseStatusRoute
  '/api/public/create-case': typeof ApiPublicCreateCaseRoute
  '/api/public/upload-document': typeof ApiPublicUploadDocumentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/fr'
    | '/robots.txt'
    | '/ru'
    | '/sitemap.xml'
    | '/$locale/$slug'
    | '/api/public/case-status'
    | '/api/public/create-case'
    | '/api/public/upload-document'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/en'
    | '/fr'
    | '/robots.txt'
    | '/ru'
    | '/sitemap.xml'
    | '/$locale/$slug'
    | '/api/public/case-status'
    | '/api/public/create-case'
    | '/api/public/upload-document'
  id:
    | '__root__'
    | '/'
    | '/en'
    | '/fr'
    | '/robots.txt'
    | '/ru'
    | '/sitemap.xml'
    | '/$locale/$slug'
    | '/api/public/case-status'
    | '/api/public/create-case'
    | '/api/public/upload-document'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRoute: typeof EnRoute
  FrRoute: typeof FrRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RuRoute: typeof RuRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LocaleSlugRoute: typeof LocaleSlugRoute
  ApiPublicCaseStatusRoute: typeof ApiPublicCaseStatusRoute
  ApiPublicCreateCaseRoute: typeof ApiPublicCreateCaseRoute
  ApiPublicUploadDocumentRoute: typeof ApiPublicUploadDocumentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ru': {
      id: '/ru'
      path: '/ru'
      fullPath: '/ru'
      preLoaderRoute: typeof RuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$slug': {
      id: '/$locale/$slug'
      path: '/$locale/$slug'
      fullPath: '/$locale/$slug'
      preLoaderRoute: typeof LocaleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/case-status': {
      id: '/api/public/case-status'
      path: '/api/public/case-status'
      fullPath: '/api/public/case-status'
      preLoaderRoute: typeof ApiPublicCaseStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-case': {
      id: '/api/public/create-case'
      path: '/api/public/create-case'
      fullPath: '/api/public/create-case'
      preLoaderRoute: typeof ApiPublicCreateCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload-document': {
      id: '/api/public/upload-document'
      path: '/api/public/upload-document'
      fullPath: '/api/public/upload-document'
      preLoaderRoute: typeof ApiPublicUploadDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRoute: EnRoute,
  FrRoute: FrRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RuRoute: RuRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LocaleSlugRoute: LocaleSlugRoute,
  ApiPublicCaseStatusRoute: ApiPublicCaseStatusRoute,
  ApiPublicCreateCaseRoute: ApiPublicCreateCaseRoute,
  ApiPublicUploadDocumentRoute: ApiPublicUploadDocumentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
